### PR TITLE
add .gitignore files to examples

### PR DESCRIPTION
**Pull request by jarvismartin**
This is mainly just for me. I figure it _might_ be useful in the future if there are more generated documents. If you don't think this is a good idea, please just let me know.

### CODE REVIEW

**Comment by postspectacular** [comment]
It's fine, I can merge that, but it's more interesting that you're getting yarn.lock files in these folders. It doesn't create them on my machine... (yarn 1.3.2). Maybe it has to do that I've run `yarn install` & `lerna bootstrap` from the project root dir... will do some tests

**Comment by jarvismartin** [comment]
I'm just blindly following instructions, right?  Each README tells me to clone, CD into the dir, `yarn install`, etc. When I'm in the example dir, yarn install is reading the `package.json` file and installing. So, I get a `yarn.lock` file per directory.
Adding a `.gitignore` to each directory is how I usually do things, but I thought it could be more useful at some point in the future IF more gets added, or something. I don't know. I do realize that at this point all I'm doing is changing a yarn.lock file for a .gitignore, which is a wash. :D

**Comment by postspectacular** [comment]
yes, so my prev assumption was correct. because this whole repo is a yarn workspace, it doesn't actually create a `node_modules` dir or lock file for the examples if you follow build instructions in the [main readme](https://github.com/thi-ng/umbrella#building). However, unless you first have built everything from source, the build instructions for the examples will cause a standard module download from npm... never knew that :) Merging your changes now and updating `make-example`

**Comment by postspectacular** [comment]
oki, done: 65f794f6f9560a93abd901355461f76ea0c18728

**Comment by postspectacular** [comment]
> Adding a .gitignore to each directory is how I usually do things

FWIW that's what I usually have done too, but ran into some problems with yarn when it comes to publishing. there's some issue with including supposedly ignored files into the published artefact. solved it by only having a root level .gitignore.

**Pull request merged**
