### PR TITLE
docs(dsp): fixed readme links

### PR DESCRIPTION
**Pull request by Mike-Dax**
Just fixes a couple incorrect links in the README.

### CODE REVIEW

**Comment by postspectacular** [comment]
Hi @Mike-Dax - thank you - alas any changes to readme's in this repo should be done to the `tpl.readme.md` files, since all the `README.md` docs are generated. See:

https://github.com/thi-ng/umbrella/blob/74518d1017852c1a4d2f0e749f8f0f2cb9123995/packages/dsp/README.md?plain=1#L1

..and here:

https://github.com/thi-ng/umbrella/blob/develop/CONTRIBUTING.md#changes-to-readme-files

Pls let me know if you're ok to change this, else can also do it myself... 🙏

**Comment by postspectacular** [comment]
Wow! That was quick! :) thanks again!

**Comment by Mike-Dax** [comment]
Ah sorry, I thought I did that correctly but it seems the build script didn't generate the actual README.md correctly, erroring with the below:

```
shasum: ../../assets/banners/thing-dsp.svg: No such file or directory
Command failed: shasum ../../assets/banners/thing-dsp.svg
shasum: ../../assets/banners/thing-dsp.svg: No such file or directory
```

Shows me for trying to make a quick change and not reading properly. I'm struggling to find documentation for generating those banner assets so the README build doesn't error?

**Comment by postspectacular** [comment]
It's ok, don't worry - I just realized that banner issue too - only works if you've got the [thi.ng/fontgen](https://github.com/thi-ng/font) built and generated the banners. Will do it myself, since also using this opportunity to do a few other edits in that DSP readme... thanks again!

**Pull request merged**
