### PR TITLE
typo in readme

### PR DESCRIPTION
**Pull request by nkint**

### CODE REVIEW

**Comment by postspectacular** [comment]
Hi @nkint - thanks for this, but could you please:

1. do the PR against the `develop` branch (always)
2. make the fix in `README.tpl.md` file (since `README.md` files are now generated from those template files)

Also see: [Wiki](https://github.com/thi-ng/umbrella/wiki/README-generation-and-repo-specific-package-metadata)

**Comment by postspectacular** [comment]
@nkint if that's too much work, I can do it myself, just let me know... grazie! :)

**Comment by nkint** [comment]
was fast and dirty, sorry - I am in a rush, I will do it in the weekend (busy week) if not too late

**Comment by postspectacular** [comment]
@nkint null problemo! :)

**Comment by postspectacular** [comment]
Fixed now in f93b6dd4a0eeb8f493fd269325a25a1661dd2acb

**Pull request closed without merging**
