### PR TITLE
fix(webgl): unbind texture after configured

### PR DESCRIPTION
**Pull request by stwind**
Just for symmetrical completeness ...

### CODE REVIEW

**Comment by postspectacular** [comment]
Thanks @stwind - you're right, symmetry is good here! Before I merge this though, we both should look for any references (e.g. in `defMultipass()` and elsewhere) where there's a possibility that some existing code assumes a texture to be bound after creation. I don't think there is, but wont hurt to double check. Just a few days ago I ran into an issue in `readTexture()` which wasn't getting updated after your FBO PR, still assumed the old behavior and therefore produced some very weird errors which took me quite long to figure out... https://github.com/thi-ng/umbrella/commit/6cb4448f75811e9a266ff81065da03ccdf138b6d

**Comment by stwind** [comment]
@postspectacular Yeah, you are right. I should check the existing call sites for compatibility. 

Here are the call sites I found:

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/packages/webgl/src/multipass.ts#L78-L88

These textures are later attached to FBOs, so it should be fine here.

---

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/examples/webgl-cubemap/src/index.ts#L77-L89

Theses are directly attached to a model.

---

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/examples/webgl-grid/src/index.ts#L67-L78

This one is also created in `compileModel`

---

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/examples/webgl-msdf/src/index.ts#L101-L107

Also in model definition.

---

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/examples/webgl-ssao/src/index.ts#L71-L89

These are all attached to FBOs or for model definition.

---

https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/examples/webgl-ssao/src/index.ts#L133-L144

In model definition.

---

These are from a quick grep in the source code. Can anywhere still be missing?

**Comment by stwind** [comment]
Or is it really necessary to unbind a texture? Actually the reason I make this PR is that I ran into some strange textures reading bug, and I suspect maybe there is some textures left unbound somewhere and check every places. Then I think it may also be a good idea to unbind it after creation.

But it also seems that just making sure to bind a texture before using it would be good enough. Also noticed that [`webgl.draw()`](https://github.com/thi-ng/umbrella/blob/a8bd0cf2770f22b19837b411b38f92d2bdd23953/packages/webgl/src/draw.ts#L7) leaves textures unbound after draw. Is it by this same decision?

**Comment by postspectacular** [comment]
@stwind cleaning up after configuring is good i think, but for `draw()` I still would still like to do more testing/benchmarking to see if unbinding them after each draw call will have any negative impact. In fact, `draw` itself should be updated at some point (or maybe replaced by some higher-level alternative) to also perform some form of GL state diffing to check if textures and/or shaders need to be changed/switched at all...

**Comment by postspectacular** [comment]
Hey @stwind - i just added some new options related to this PR:

1) The `configure()` methods of `FBO`, `RBO` and `Texture` now take an additional optional arg to disable unbinding. In multipass situations this can be quite useful (just ran into it)... (https://github.com/thi-ng/umbrella/commit/0e5cc2bc5b632c7d418715c936d4cc6152b4a57c)
2) Added `DrawOpts` for `draw()` to allow user override for binding/unbinding textures & shader. Again, useful for multipass situs... (https://github.com/thi-ng/umbrella/commit/27021facca516e3d9c598f017819fe0314c72af4)

Both are released as part of v3.1.1

**Comment by stwind** [comment]
@postspectacular Cool! That would be useful. Thanks!

**Pull request merged**
